name: CI Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '~1.19.0'

      - name: Build p2m-reader
        run: |
          cd ./go && go install ./cmd/p2m-reader

      - name: Run p2m-reader and check output
        run: |
          p2m-reader < example/example-meta-only.msg 2>&1 | grep -q "Microsoft"

      - name: Build pdf2msgpack
        run: |
          make

      # Not a rigorous test, but a quick check to ensure the build at least runs.
      - name: Run and check output
        run: |
          diff <(./pdf2msgpack --meta-only example/example.pdf) example/example-meta-only.msg
